name: Publish Package
on:
  push:
    branches:
      - main
jobs:
  publish-package:
    if: ${{ github.event.head_commit.message }} == "!Publish"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install --upgrade pip
      - run: pip install build
      - run: pip install twine
      - run: python -m build --wheel
      - run: twine upload dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN}}