name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@main
        with:
          python-version: "3.10"
          enable-pep582: true
      - run: pdm install
      - run: pdm publish --username __token__ --password ${{ secrets.PYPI_TOKEN }}
